# Generated by Django 4.0.1 on 2022-02-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messagre',
            new_name='message',
        ),
    ]
